package com.alexa.dem;

import java.util.Date;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="CricketManagerTable")
public class CricketManagerTable {
    
    private String dataPlayerName;
    private int runsValue;
    
    
    
    
    @DynamoDBHashKey(attributeName="DataPlayer")  
    public String getPlayer() {return dataPlayerName; }
    public void setPlayer(String dataPlayerName) { this.dataPlayerName = dataPlayerName; }
    /*
    @DynamoDBRangeKey(attributeName="Category")  
    public String getCategory() {return dataItem; }
    public void setCategory(String dataItem) { this.dataItem = dataItem; }
    */
	
    @DynamoDBAttribute(attributeName="DataRuns")  
    public double getRuns() { return dataValue; }
    public void setRuns(int runsValue) { this.runsValue = runsValue; }
    /*
    @DynamoDBIgnore
    public String getSomeProp() { return someProp;}
    public void setSomeProp(String someProp) {this.someProp = someProp;}
    */
}
